# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 06:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text=b'name of course', max_length=200)),
                ('code', models.CharField(help_text=b'course code', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(help_text=b'detail of the option', max_length=200)),
                ('selected', models.BooleanField(help_text=b'if option has been selected')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[(b'o', b'Objective'), (b't', b'Theory')], help_text=b'shows the type of question', max_length=200)),
                ('detail', models.CharField(help_text=b'Question detail', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text=b'title of test', max_length=20, null=True)),
                ('description', models.TextField(help_text=b'description of test')),
                ('instruction', models.TextField(help_text=b'instruction of test')),
                ('duration', models.DurationField(default=datetime.timedelta(0, 3600), help_text=b'How long will the test last', null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='app.Course')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.Test'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app.Question'),
        ),
    ]
