# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170810_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_number', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='password',
            field=models.CharField(default='animated50', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
