# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170810_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'photos/%Y/%m/%d'),
        ),
    ]
