# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_questionimage_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimage',
            name='number',
            field=models.CharField(max_length=5),
        ),
    ]
