# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170816_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionimage',
            name='number',
        ),
    ]
